export const projects = [
  { name: "Taskora", category: "Product intelligence", theme: "taskora", statement: "Feedback, with a way forward.", description: "A customer-feedback analysis pipeline that turns customer concerns into product suggestions grounded in user feedback.", technologies: ["Next.js", "TypeScript", "Supabase", "Gemini API"], highlights: ["Connected customer feedback to Gemini-generated product suggestions and stored feedback and insights in Supabase.", "Built 10+ responsive dashboard views to surface product intelligence.", "Iterated with 50+ early adopters, driving 20% week-over-week engagement growth."], github: "https://github.com/milllsdev/taskora", live: "https://taskora-sepia.vercel.app/" },
  { name: "DreamTrip AI", category: "Selected project", theme: "dreamtrip", statement: "DreamTrip AI.", description: "Explore DreamTrip AI through the live project.", technologies: [], highlights: [], live: "https://dreamtrip-ai-xi.vercel.app/", github: undefined },
  { name: "Rendo", category: "Creative tools", theme: "rendo", statement: "An idea. A video. Your voice.", description: "An AI short-form video editor that transforms prompts, media, and links into creator-ready videos through automated generation pipelines.", technologies: ["Next.js", "TypeScript", "React", "Tailwind CSS"], highlights: ["Architected media import, prompt-based generation, and a creator dashboard.", "Iterated on onboarding, media import, and generation with feedback from 15 early users."], github: "https://github.com/milllsdev/short-editor", live: undefined },
  { name: "Fintech Dashboard", category: "Financial software", theme: "fintech", statement: "Connected accounts. Clearer spending.", description: "A full-stack fintech application that securely links bank accounts with Plaid and visualizes transaction data and spending by category.", technologies: ["Next.js", "FastAPI", "Supabase", "Plaid API"], highlights: ["Built FastAPI token exchange, REST endpoints, and transaction-categorization logic across linked accounts.", "Connected a Next.js dashboard to the backend, with persistent per-user storage in Supabase.", "Deployed the FastAPI backend to Render with environment-based secrets management."], github: "https://github.com/milllsdev/fintech-dashboard", live: undefined }
];
export const experience = [
  { company: "MS-CC Hackathon", role: "First Runner-Up", date: "March 2026", location: "West Virginia State University, West Virginia", points: ["Engineered a Python Multi-Sensor Data Reliability & Attack Simulation System, cross-validating a PM2.5 sensor against two neighboring sensors using 9+ statistical reliability metrics.", "Implemented and tested 10 attack simulations, including spike, drift, noise, flatline, and replay, within 24 hours.", "Presented architecture and engineering tradeoffs; earned First Runner-Up among 30+ teams."] },
  { company: "Ecobank Ghana", role: "Technical Product Intern", date: "March – July 2025", location: "Remote", points: ["Tested mobile and web banking workflows end to end with Chrome DevTools and Postman, identifying 12 defects and edge cases before release.", "Queried customer and transaction data using SQL to identify 8 recurring friction points across banking, payments, and onboarding.", "Reproduced bugs and validated fixes with engineering, contributing to an 18% improvement in onboarding completion.", "Benchmarked the technical implementation of 8+ competing banking applications."] },
  { company: "Blueticks Technology", role: "Frontend Engineering Intern", date: "January – May 2024", location: "Accra, Ghana", points: ["Shipped 20+ reusable responsive React components with JavaScript and Tailwind CSS, reducing rebuild time by 30%.", "Resolved 15+ issues across browsers and screen sizes.", "Integrated frontend workflows with REST APIs alongside backend developers, unblocking 10+ releases."] }
];
export const skillGroups = [
  { title: "Languages", items: ["Python", "JavaScript", "TypeScript", "SQL", "Java", "C++"] },
  { title: "Frameworks", items: ["React", "Next.js", "FastAPI", "Node.js", "Tailwind CSS"] },
  { title: "Databases & tools", items: ["PostgreSQL", "MongoDB", "Supabase", "Docker", "Git", "Figma", "Postman", "Vercel"] }
];
export const activities = [
  { name: "Adobe Student Ambassador", role: "Tier One", location: "Remote" },
  { name: "ColorStack", role: "Member", location: "Livingstone College" },
  { name: "CodePath", role: "Member", location: "Livingstone College" },
  { name: "Black Student Leadership Network", role: "Ambassador", location: "Livingstone College" }
];
